# Day 14 - Smart Agent Project: AI Article Writer
from flask import Flask, render_template, request, redirect
import requests
import os
from datetime import datetime

app = Flask(__name__)

ARTICLES_FOLDER = "articles"
if not os.path.exists(ARTICLES_FOLDER):
    os.makedirs(ARTICLES_FOLDER)

def generate_article(topic, tone, length):
    """Generate article using Ollama or mock mode"""
    
    prompt = f"""Write a {length} article about "{topic}".
Tone: {tone}.
Structure:
1. Catchy Title
2. Introduction (2-3 sentences)
3. 3 Key Points with explanations
4. Conclusion
Write in English."""
    
    try:
        url = "http://localhost:11434/api/generate"
        data = {
            "model": "llama3.1",
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.8, "num_predict": 800}
        }
        response = requests.post(url, json=data, timeout=60)
        result = response.json()
        return result["response"].strip()
    except:
        return generate_mock_article(topic, tone, length)

def generate_mock_article(topic, tone, length):
    """Smart mock article generator"""
    
    titles = {
        "python": "Python: The Language of the Future",
        "ai": "Artificial Intelligence: Transforming Our World",
        "business": "Business Growth Strategies for 2024",
        "health": "The Science of Healthy Living",
        "money": "Financial Freedom: A Practical Guide"
    }
    
    title = titles.get(topic.lower(), f"The Ultimate Guide to {topic.title()}")
    
    article = f"""{title}

Introduction:
In today's rapidly evolving world, understanding {topic} has become essential. This article explores the key aspects that everyone should know.

Key Point 1: The Foundation
The foundation of {topic} lies in consistent learning and application. Experts agree that mastering the basics leads to long-term success.

Key Point 2: Practical Applications
Real-world applications of {topic} are everywhere. From daily life to professional careers, the impact is undeniable.

Key Point 3: Future Trends
Looking ahead, {topic} will continue to shape industries. Staying updated ensures you remain competitive.

Conclusion:
Whether you are a beginner or expert, {topic} offers endless opportunities. Start your journey today and see the results.

---
Generated by Smart Agent v2.0
Tone: {tone} | Length: {length} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
    return article

def save_article(topic, content):
    """Save article to file"""
    filename = f"{ARTICLES_FOLDER}/article_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    return filename

@app.route("/")
def home():
    return render_template("writer.html")

@app.route("/generate", methods=["POST"])
def generate():
    topic = request.form["topic"]
    tone = request.form.get("tone", "professional")
    length = request.form.get("length", "medium")
    
    article = generate_article(topic, tone, length)
    filename = save_article(topic, article)
    
    return render_template("writer.html", 
                         article=article, 
                         topic=topic,
                         filename=filename)

@app.route("/articles")
def list_articles():
    files = os.listdir(ARTICLES_FOLDER)
    files.sort(reverse=True)
    articles = []
    for f in files:
        if f.endswith(".txt"):
            with open(f"{ARTICLES_FOLDER}/{f}", "r", encoding="utf-8") as file:
                first_line = file.readline().strip()
            articles.append({"file": f, "title": first_line})
    return render_template("articles.html", articles=articles)

if __name__ == "__main__":
    print("=" * 50)
    print("SMART AGENT: AI Article Writer")
    print("Open: http://localhost:5000")
    print("=" * 50)
    app.run(host="0.0.0.0", port=5000, debug=True)

